CREATE TABLE IF NOT EXISTS "user" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "username" varchar(128) DEFAULT NULL,
    "nickname" varchar(128) DEFAULT NULL,
    "password" varchar(128) DEFAULT NULL,
    "login_token" varchar(128) DEFAULT NULL,
    "register_time" datetime DEFAULT NULL,
    "last_login_time" datetime DEFAULT NULL,
    "gender" varchar(128) DEFAULT NULL,
    "email" varchar(128) DEFAULT NULL,
    "address" varchar(128) DEFAULT NULL,
    "is_valid" tinyint(1) DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_validation_code" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" int DEFAULT NULL,
    "validation_code" varchar(8) DEFAULT NULL,
    "generated_time" datetime DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "user_login_token" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "user_id" int DEFAULT NULL,
    "login_token" varchar(8) DEFAULT NULL,
    "login_time" datetime DEFAULT NULL,
    PRIMARY KEY ("id")
);

CREATE TABLE IF NOT EXISTS "friend_invitation" (
    "id" int NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    "sender_user_id" int DEFAULT NULL,
    "receiver_user_id" int DEFAULT NULL,
    "message" varchar(255) DEFAULT NULL,
    "create_time" datetime DEFAULT NULL,
    "status" varchar(50) DEFAULT NULL,
    PRIMARY KEY ("id")
);
