name: test
on: [push]
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'corretto'
          java-version: '21'
      - uses: shogo82148/actions-setup-mysql@v1
        with:
          mysql-version: "8.0"
      - run: mysql -uroot < init.sql
      - run: mvn test
